# Generated by Django 4.2.30 on 2026-04-17 17:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('case_number', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Номер дела')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('active', 'Активное'), ('on_hold', 'Приостановлено'), ('closed', 'Закрыто'), ('archived', 'В архиве')], default='new', max_length=20, verbose_name='Статус')),
                ('category', models.CharField(choices=[('civil', 'Гражданское'), ('criminal', 'Уголовное'), ('corporate', 'Корпоративное'), ('family', 'Семейное'), ('labor', 'Трудовое'), ('property', 'Имущественное'), ('bankruptcy', 'Банкротство'), ('other', 'Прочее')], max_length=30, verbose_name='Категория')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('court_name', models.CharField(blank=True, max_length=255, verbose_name='Суд')),
                ('court_case_number', models.CharField(blank=True, max_length=100, verbose_name='Номер дела в суде')),
                ('opened_at', models.DateField(default=datetime.date.today, verbose_name='Дата открытия')),
                ('closed_at', models.DateField(blank=True, null=True, verbose_name='Дата закрытия')),
                ('expected_close_date', models.DateField(blank=True, null=True, verbose_name='Планируемая дата закрытия')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Часовая ставка (руб.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_lawyers', models.ManyToManyField(blank=True, limit_choices_to={'role': 'lawyer'}, related_name='assigned_cases', to=settings.AUTH_USER_MODEL, verbose_name='Юристы')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='clients.client', verbose_name='Клиент')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cases', to=settings.AUTH_USER_MODEL)),
                ('lead_lawyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_cases', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный юрист')),
            ],
            options={
                'verbose_name': 'Дело',
                'verbose_name_plural': 'Дела',
                'ordering': ['-created_at'],
            },
        ),
    ]
