# Generated by Django 4.2.30 on 2026-04-17 19:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_case_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
