# Generated by Django 4.2.30 on 2026-07-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_case_key_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='opposing_party',
            field=models.CharField(blank=True, help_text='ФИО или название организации — для проверки конфликта интересов', max_length=255, verbose_name='Противоположная сторона'),
        ),
        migrations.AddField(
            model_name='case',
            name='opposing_party_inn',
            field=models.CharField(blank=True, max_length=20, verbose_name='ИНН противоположной стороны'),
        ),
    ]
