# Generated by Django 4.2.30 on 2026-07-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_case_opposing_party_case_opposing_party_inn'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status'], name='cases_case_status_5f99d2_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['category'], name='cases_case_categor_df1bb8_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['key_deadline'], name='cases_case_key_dea_5ef4a8_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['-created_at'], name='cases_case_created_a2f158_idx'),
        ),
    ]
