# Generated by Django 4.2.30 on 2026-07-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['-timestamp'], name='audit_activ_timesta_7c75b8_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['resource_type', 'resource_uuid'], name='audit_activ_resourc_3d5106_idx'),
        ),
    ]
