# Generated by Django 4.2.30 on 2026-04-17 17:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Номер счёта')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлен'), ('paid', 'Оплачен'), ('overdue', 'Просрочен'), ('cancelled', 'Отменён')], default='draft', max_length=20)),
                ('issue_date', models.DateField(default=datetime.date.today, verbose_name='Дата выставления')),
                ('due_date', models.DateField(verbose_name='Срок оплаты')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма без НДС')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='НДС (%)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма НДС')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Итого')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='cases.case', verbose_name='Дело')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='clients.client', verbose_name='Клиент')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Счёт',
                'verbose_name_plural': 'Счета',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Часы')),
                ('description', models.TextField(verbose_name='Описание работ')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ставка (руб./час)')),
                ('is_billable', models.BooleanField(default=True, verbose_name='Оплачиваемое')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='cases.case', verbose_name='Дело')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='billing.invoice', verbose_name='Счёт')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to=settings.AUTH_USER_MODEL, verbose_name='Юрист')),
            ],
            options={
                'verbose_name': 'Запись времени',
                'verbose_name_plural': 'Записи времени',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Кол-во (часы/ед.)')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.invoice')),
                ('time_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_item', to='billing.timeentry')),
            ],
            options={
                'verbose_name': 'Строка счёта',
                'verbose_name_plural': 'Строки счёта',
            },
        ),
    ]
