# Generated by Django 4.2.30 on 2026-07-27 08:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_case_opposing_party_case_opposing_party_inn'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0002_invoicepayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='Абонентское юридическое обслуживание', max_length=255, verbose_name='Описание услуги')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма без НДС')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='НДС (%)')),
                ('frequency', models.CharField(choices=[('monthly', 'Ежемесячно'), ('quarterly', 'Ежеквартально')], default='monthly', max_length=20, verbose_name='Периодичность')),
                ('day_of_month', models.PositiveSmallIntegerField(default=1, help_text='1–28; в коротких месяцах переносится на последний день', verbose_name='День выставления')),
                ('payment_term_days', models.PositiveSmallIntegerField(default=14, verbose_name='Срок оплаты (дней)')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Действует с')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Действует по')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('last_generated', models.DateField(blank=True, null=True, verbose_name='Последний счёт')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_invoices', to='cases.case', verbose_name='Дело')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recurring_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Повторяющийся счёт',
                'verbose_name_plural': 'Повторяющиеся счета',
                'ordering': ['-created_at'],
            },
        ),
    ]
