# Generated by Django 4.2.30 on 2026-07-27 09:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_case_cases_case_status_5f99d2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0004_invoice_billing_inv_status_996e80_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('category', models.CharField(choices=[('state_fee', 'Госпошлина'), ('expert', 'Экспертиза'), ('notary', 'Нотариус'), ('travel', 'Транспорт и проживание'), ('post', 'Почта и курьер'), ('other', 'Прочее')], default='other', max_length=20, verbose_name='Категория')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('is_billable', models.BooleanField(default=True, help_text='Снимите, если расход остаётся за фирмой', verbose_name='Перевыставить клиенту')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='expenses/%Y/%m/', verbose_name='Чек / подтверждение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='cases.case', verbose_name='Дело')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='billing.invoice', verbose_name='Счёт')),
            ],
            options={
                'verbose_name': 'Расход по делу',
                'verbose_name_plural': 'Расходы по делу',
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['case', '-date'], name='billing_cas_case_id_b84852_idx')],
            },
        ),
    ]
