# Generated by Django 4.2.30 on 2026-07-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_telegramlinktoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='calendar_token',
            field=models.UUIDField(blank=True, help_text='Секретная ссылка на календарь; отзывается перевыпуском', null=True, unique=True, verbose_name='Токен ICS-подписки'),
        ),
    ]
