# Generated by Django 4.2.30 on 2026-07-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_calendar_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('lawyer', 'Юрист'), ('assistant', 'Помощник')], default='lawyer', max_length=20, verbose_name='Роль'),
        ),
    ]
