# Generated by Django 4.2.30 on 2026-07-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='recurrence',
            field=models.CharField(choices=[('none', 'Не повторять'), ('weekly', 'Каждую неделю'), ('biweekly', 'Раз в две недели'), ('monthly', 'Каждый месяц'), ('quarterly', 'Раз в квартал')], default='none', help_text='После выполнения автоматически создаётся следующая задача', max_length=20, verbose_name='Повторение'),
        ),
    ]
