# Generated by Django 4.2.30 on 2026-04-17 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(choices=[('individual', 'Физическое лицо'), ('legal_entity', 'Юридическое лицо')], max_length=20, verbose_name='Тип клиента')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('passport_number', models.CharField(blank=True, max_length=50, verbose_name='Паспорт')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='ИНН')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Название компании')),
                ('registration_number', models.CharField(blank=True, max_length=100, verbose_name='ОГРН')),
                ('legal_address', models.TextField(blank=True, verbose_name='Юридический адрес')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('position', models.CharField(blank=True, max_length=150, verbose_name='Должность')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_persons', to='clients.client')),
            ],
            options={
                'verbose_name': 'Контактное лицо',
                'verbose_name_plural': 'Контактные лица',
                'ordering': ['-is_primary', 'last_name'],
            },
        ),
    ]
